includes:
  - https://github.ibm.com/cloud-docs/apps
  - https://github.ibm.com/cloud-docs/analytics-engine-cli-plugin
  - https://github.ibm.com/cloud-docs/app-configuration
  - https://github.ibm.com/cloud-docs/cephaas
  - https://github.ibm.com/cloud-docs/cis
  - https://github.ibm.com/cloud-docs/cloud-object-storage
  - https://github.ibm.com/cloud-docs/Cloudant
  - https://github.ibm.com/cloud-docs/codeengine
  - https://github.ibm.com/cloud-docs/ContinuousDelivery
  - https://github.ibm.com/cloud-docs/containers
  - https://github.ibm.com/cloud-docs/data-virtualization
  - https://github.ibm.com/cloud-docs/databases-cli-plugin
  - https://github.ibm.com/cloud-docs/dl
  - https://github.ibm.com/cloud-docs/dns-svcs
  - https://github.ibm.com/cloud-docs/event-notifications
  - https://github.ibm.com/cloud-docs/EventStreams
  - https://github.ibm.com/cloud-docs/hs-crypto
  - https://github.ibm.com/cloud-docs/hp-virtual-servers
  - https://github.ibm.com/cloud-docs/key-protect
  - https://github.ibm.com/cloud-docs/metrics-router-cli
  - https://github.ibm.com/cloud-docs/monitor-cli-plugin
  - https://github.ibm.com/cloud-docs/openpages
  - https://github.ibm.com/cloud-docs/privileged-access-gateway
  - https://github.ibm.com/cloud-docs/Registry
  - https://github.ibm.com/cloud-docs/satellite
  - https://github.ibm.com/cloud-docs/schematics
  - https://github.ibm.com/cloud-docs/secrets-manager
  - https://github.ibm.com/cloud-docs/security-compliance
  - https://github.ibm.com/cloud-docs/transit-gateway
  - https://github.ibm.com/cloud-docs/vpc-infrastructure-cli-plugin